export const AUTOGEN_COMMENT = "# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n";
export const ENVIO_SCHEMA_COMMENT = "# yaml-language-server: $schema=../../../node_modules/envio/evm.schema.json\n";
