import path from "node:path";

export const AUTOGEN_COMMENT = "# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n";
export const GRAPH_DIR = path.join(__dirname, "../src/graph");
export const SCHEMA_DIR = path.join(__dirname, "../src/schema");
